### ISSUE TITLE
Create an issue through the issue_tracking project

### ISSUE THREAD

**Issue by lmangall** [ft-transcendence-inc/ft_transcendence#1]
Creating and adding through the project
=> it look like it would replace linear

@552020  @lmangall  please check it out on the project tab of the repo

Screenshot:
![Image](https://github.com/ft-transcendence-inc/ft_transcendence/assets/107299611/5b33f81b-3035-4648-9210-95498cd869af)

**Comment by 552020** [comment]
> Creating and adding through the project
> => it look like it would replace linear

This was clear! :-)

**Comment by 552020** [comment]
> [@552020](https://github.com/552020) [@lmangall](https://github.com/lmangall) please check it out on the project tab of the repo

I did. Why did you tag only me and you?

**Comment by 552020** [comment]
Is it possible to create sub-issues? @lmangall

**Comment by lmangall** [comment]
Yes, I added a sub and detailed the process on the "draft" you created
tagging now @dantol29  (now possible because he accepted)
